import Head from "next/head";
import Link from "next/link";

import styles from "../../styles/PokeInfo.module.scss";

import {
  Pokemon,
  PokemonAbility,
  PokemonInfo,
  PokemonSpecies,
  PokemonStats,
  PokemonType,
} from "@/interfaces/interfaces";

import PokeInfoCard from "./PokeInfoCard";
import PokeInfoStats from "./PokeInfoStats";
import PokeInfoHeader from "./PokeInfoHeader";

const PokeInfo = ({ pokemon }: PokemonInfo) => {
  if (pokemon?.length === 0) {
    return (
      <>
        <Head>
          <title>Error Pokemon ID</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/pokeball.svg" />
        </Head>
        <div className={styles.error}>
          <p>Pokemon ID doesn't exist</p>

          <Link href="/">
            <button className={styles.buttonError}>Back to home</button>
          </Link>
        </div>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>{`${
          pokemon?.[0].name.charAt(0).toUpperCase() +
          pokemon?.[0].name.slice(1)!
        } #${pokemon?.[0].id} - Pokedex Next App`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokeball.svg" />
      </Head>

      {pokemon?.map((poke: Pokemon) => {
        const { name, id, height, weight } = poke;

        const types = poke.pokemon_v2_pokemontypes.map((type: PokemonType) => {
          return type.pokemon_v2_type.name;
        });

        const abilities = poke.pokemon_v2_pokemonabilities.map(
          (ability: PokemonAbility) => {
            return ability.pokemon_v2_ability.name;
          }
        );

        const stats = poke.pokemon_v2_pokemonstats.map((stat: PokemonStats) => {
          return {
            base_stat: stat.base_stat,
            name: stat.pokemon_v2_stat.name,
          };
        });

        const evolution =
          poke.pokemon_v2_pokemonspecy.pokemon_v2_evolutionchain.pokemon_v2_pokemonspecies.map(
            (evo: PokemonSpecies) => {
              const { name, id, is_baby } = evo;

              const flavor_text =
                evo.pokemon_v2_pokemonspeciesflavortexts[0]?.flavor_text || "";

              return {
                name,
                is_baby,
                id_evo: id,
                flavor_text,
              };
            }
          );

        let prevPokemon = id - 1,
          nextPokemon = id + 1;

        return (
          <div className={styles.container} key={poke.id}>
            <PokeInfoHeader
              prevPokemon={prevPokemon}
              nextPokemon={nextPokemon}
              types={types}
              id={id}
              name={name}
            />

            <div className={styles.divComponents}>
              <PokeInfoCard
                prevPokemon={prevPokemon}
                nextPokemon={nextPokemon}
                id={id}
                types={types}
                height={height}
                weight={weight}
                abilities={abilities}
              />

              <PokeInfoStats
                stats={stats}
                evolution={evolution}
                types={types}
                id={id}
              />
            </div>
          </div>
        );
      })}
    </>
  );
};

export default PokeInfo;
