import PokeInfo from "@/components/PokeInfo";
import { POKEMON_QUERY } from "@/graphql/queries";
import { useRouter } from "next/router";
import { useQuery } from "@apollo/client";
import { Pokemon } from "@/interfaces/interfaces";
import Head from "next/head";

const Pokedex = () => {
  const router = useRouter();

  const id = router.query.id;

  const { data, loading } = useQuery(POKEMON_QUERY, { variables: { id } });

  const pokemon = data?.pokemon_v2_pokemon.map((pokemon: Pokemon) => {
    return pokemon;
  });

  return (
    <>
      {loading ? (
        <>
          <Head>
            <title>Loading...</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/pokeball.svg" />
          </Head>

          <p className="loading">Loading...</p>
        </>
      ) : (
        <PokeInfo pokemon={pokemon} />
      )}
    </>
  );
};

export default Pokedex;
