import Head from "next/head";

import styles from "@/styles/Home.module.scss";

import Header from "@/components/Header";
import Pagination from "@/components/Pagination";
import PokemonsGrid from "@/components/PokemonsGrid";

import { GetServerSideProps } from "next";

import { client, POKEMONS_QUERY } from "@/graphql/queries";

import { HomeProps, Pokemons } from "@/interfaces/interfaces";

export const getServerSideProps: GetServerSideProps<HomeProps> = async (
  context
) => {
  const { page = "1" } = context.query;
  const pageNumber = Number(page) || 1;

  const limit = 16;
  const offset = (pageNumber - 1) * limit;

  const { data } = await client.query({
    query: POKEMONS_QUERY,
    variables: { limit, offset },
  });

  const pokemons = data.pokemon_v2_pokemon.map((poke: Pokemons) => {
    return poke;
  });

  const totalPokemons = 1008;
  const totalPages = Math.ceil(totalPokemons / limit);

  if (pageNumber > totalPages) {
    return {
      redirect: {
        destination: `/?page=${totalPages}`,
        permanent: false,
      },
    };
  }

  return {
    props: {
      data: pokemons,
      page: pageNumber,
      totalPages,
    },
  };
};

const Home = ({ data, page, totalPages }: HomeProps) => {
  return (
    <>
      <Head>
        <title>Pokedex Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokeball.svg" />
      </Head>
      <Header />

      <div className={styles.container}>
        <PokemonsGrid data={data} />

        <Pagination page={page} totalPages={totalPages} />
      </div>
    </>
  );
};

export default Home;
